### ISSUE TITLE
CUB200 experiment running into error

### ISSUE THREAD

**Issue by toshi2k2** [sangwon79/AGS-CL#1]
`python ./main.py --dataset CUB200 --trainer gs --lamb 1.5 --mu 0.5 --rho 0.1 --eta 0.9`
```
Load data...
Load start!
Load finished!
Time elapse: 0

Task info = [(0, 20), (1, 20), (2, 20), (3, 20), (4, 20), (5, 20), (6, 20), (7, 20), (8, 20), (9, 20)]
----------------------------------------------------------------------------------------------------
AlexNet(
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
  (avgpool): AdaptiveAvgPool2d(output_size=(6, 6))
  (dropout): Dropout(p=0.5, inplace=False)
  (conv1): Conv2d(3, 64, kernel_size=(11, 11), stride=(4, 4), padding=(2, 2))
  (conv2): Conv2d(64, 192, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
  (conv3): Conv2d(192, 384, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (conv4): Conv2d(384, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (conv5): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (fc1): Linear(in_features=9216, out_features=4096, bias=True)
  (fc2): Linear(in_features=4096, out_features=4096, bias=True)
  (last): ModuleList(
    (0): Linear(in_features=4096, out_features=20, bias=True)
    (1): Linear(in_features=4096, out_features=20, bias=True)
    (2): Linear(in_features=4096, out_features=20, bias=True)
    (3): Linear(in_features=4096, out_features=20, bias=True)
    (4): Linear(in_features=4096, out_features=20, bias=True)
    (5): Linear(in_features=4096, out_features=20, bias=True)
    (6): Linear(in_features=4096, out_features=20, bias=True)
    (7): Linear(in_features=4096, out_features=20, bias=True)
    (8): Linear(in_features=4096, out_features=20, bias=True)
    (9): Linear(in_features=4096, out_features=20, bias=True)
  )
)
Dimensions = torch.Size([64, 3, 11, 11]) torch.Size([64]) torch.Size([192, 64, 5, 5]) torch.Size([192]) torch.Size([384, 192, 3, 3]) torch.Size([384]) torch.Size([256, 384, 3, 3]) torch.Size([256]) torch.Size([256, 256, 3, 3]) torch.Size([256]) torch.Size([4096, 9216]) torch.Size([4096]) torch.Size([4096, 4096]) torch.Size([4096]) torch.Size([20, 4096]) torch.Size([20]) torch.Size([20, 4096]) torch.Size([20]) torch.Size([20, 4096]) torch.Size([20]) torch.Size([20, 4096]) torch.Size([20]) torch.Size([20, 4096]) torch.Size([20]) torch.Size([20, 4096]) torch.Size([20]) torch.Size([20, 4096]) torch.Size([20]) torch.Size([20, 4096]) torch.Size([20]) torch.Size([20, 4096]) torch.Size([20]) torch.Size([20, 4096]) torch.Size([20]) 
Num parameters = 57.8M
----------------------------------------------------------------------------------------------------
SGD (
Parameter Group 0
    dampening: 0
    lr: 0.005
    momentum: 0.9
    nesterov: False
    weight_decay: 0
) = lr: 0.005, momentum: 0.9, dampening: 0, weight_decay: 0, nesterov: False, 
----------------------------------------------------------------------------------------------------
tasknum: 0
Setting LR to 0.0050
  0%|                                                                                        | 0/15 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/mnt/sda1/my_git/wacv_21/AGS-CL/LargeScale_AGS/./main.py", line 138, in <module>
    myTrainer.train(train_loader, test_loader, t)
  File "/mnt/sda1/my_git/wacv_21/AGS-CL/LargeScale_AGS/trainer/gs.py", line 83, in train
    for samples in tqdm(self.train_iterator):
  File "/home/toshi/base/lib/python3.9/site-packages/tqdm/std.py", line 1166, in __iter__
    for obj in iterable:
  File "/home/toshi/base/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/toshi/base/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/toshi/base/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/toshi/base/lib/python3.9/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/toshi/base/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/toshi/base/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/toshi/base/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/sda1/my_git/wacv_21/AGS-CL/LargeScale_AGS/data_handler/incremental_loader.py", line 37, in __getitem__
    img = self.transform(img)
  File "/home/toshi/base/lib/python3.9/site-packages/torchvision/transforms/transforms.py", line 67, in __call__
    img = t(img)
  File "/home/toshi/base/lib/python3.9/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/toshi/base/lib/python3.9/site-packages/torchvision/transforms/transforms.py", line 823, in forward
    i, j, h, w = self.get_params(img, self.scale, self.ratio)
  File "/home/toshi/base/lib/python3.9/site-packages/torchvision/transforms/transforms.py", line 786, in get_params
    target_area = area * torch.empty(1).uniform_(scale[0], scale[1]).item()
  File "/home/toshi/base/lib/python3.9/site-packages/torch/cuda/__init__.py", line 163, in _lazy_init
    raise RuntimeError(
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
```

**Comment by hongjoon0805** [comment]
> `python ./main.py --dataset CUB200 --trainer gs --lamb 1.5 --mu 0.5 --rho 0.1 --eta 0.9`
> 
> ```
> Load data...
> Load start!
> Load finished!
> Time elapse: 0
> 
> Task info = [(0, 20), (1, 20), (2, 20), (3, 20), (4, 20), (5, 20), (6, 20), (7, 20), (8, 20), (9, 20)]
> ----------------------------------------------------------------------------------------------------
> AlexNet(
>   (relu): ReLU(inplace=True)
>   (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
>   (avgpool): AdaptiveAvgPool2d(output_size=(6, 6))
>   (dropout): Dropout(p=0.5, inplace=False)
>   (conv1): Conv2d(3, 64, kernel_size=(11, 11), stride=(4, 4), padding=(2, 2))
>   (conv2): Conv2d(64, 192, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
>   (conv3): Conv2d(192, 384, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
>   (conv4): Conv2d(384, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
>   (conv5): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
>   (fc1): Linear(in_features=9216, out_features=4096, bias=True)
>   (fc2): Linear(in_features=4096, out_features=4096, bias=True)
>   (last): ModuleList(
>     (0): Linear(in_features=4096, out_features=20, bias=True)
>     (1): Linear(in_features=4096, out_features=20, bias=True)
>     (2): Linear(in_features=4096, out_features=20, bias=True)
>     (3): Linear(in_features=4096, out_features=20, bias=True)
>     (4): Linear(in_features=4096, out_features=20, bias=True)
>     (5): Linear(in_features=4096, out_features=20, bias=True)
>     (6): Linear(in_features=4096, out_features=20, bias=True)
>     (7): Linear(in_features=4096, out_features=20, bias=True)
>     (8): Linear(in_features=4096, out_features=20, bias=True)
>     (9): Linear(in_features=4096, out_features=20, bias=True)
>   )
> )
> Dimensions = torch.Size([64, 3, 11, 11]) torch.Size([64]) torch.Size([192, 64, 5, 5]) torch.Size([192]) torch.Size([384, 192, 3, 3]) torch.Size([384]) torch.Size([256, 384, 3, 3]) torch.Size([256]) torch.Size([256, 256, 3, 3]) torch.Size([256]) torch.Size([4096, 9216]) torch.Size([4096]) torch.Size([4096, 4096]) torch.Size([4096]) torch.Size([20, 4096]) torch.Size([20]) torch.Size([20, 4096]) torch.Size([20]) torch.Size([20, 4096]) torch.Size([20]) torch.Size([20, 4096]) torch.Size([20]) torch.Size([20, 4096]) torch.Size([20]) torch.Size([20, 4096]) torch.Size([20]) torch.Size([20, 4096]) torch.Size([20]) torch.Size([20, 4096]) torch.Size([20]) torch.Size([20, 4096]) torch.Size([20]) torch.Size([20, 4096]) torch.Size([20]) 
> Num parameters = 57.8M
> ----------------------------------------------------------------------------------------------------
> SGD (
> Parameter Group 0
>     dampening: 0
>     lr: 0.005
>     momentum: 0.9
>     nesterov: False
>     weight_decay: 0
> ) = lr: 0.005, momentum: 0.9, dampening: 0, weight_decay: 0, nesterov: False, 
> ----------------------------------------------------------------------------------------------------
> tasknum: 0
> Setting LR to 0.0050
>   0%|                                                                                        | 0/15 [00:00<?, ?it/s]
> Traceback (most recent call last):
>   File "/mnt/sda1/my_git/wacv_21/AGS-CL/LargeScale_AGS/./main.py", line 138, in <module>
>     myTrainer.train(train_loader, test_loader, t)
>   File "/mnt/sda1/my_git/wacv_21/AGS-CL/LargeScale_AGS/trainer/gs.py", line 83, in train
>     for samples in tqdm(self.train_iterator):
>   File "/home/toshi/base/lib/python3.9/site-packages/tqdm/std.py", line 1166, in __iter__
>     for obj in iterable:
>   File "/home/toshi/base/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
>     data = self._next_data()
>   File "/home/toshi/base/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
>     return self._process_data(data)
>   File "/home/toshi/base/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
>     data.reraise()
>   File "/home/toshi/base/lib/python3.9/site-packages/torch/_utils.py", line 428, in reraise
>     raise self.exc_type(msg)
> RuntimeError: Caught RuntimeError in DataLoader worker process 0.
> Original Traceback (most recent call last):
>   File "/home/toshi/base/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
>     data = fetcher.fetch(index)
>   File "/home/toshi/base/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/home/toshi/base/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/mnt/sda1/my_git/wacv_21/AGS-CL/LargeScale_AGS/data_handler/incremental_loader.py", line 37, in __getitem__
>     img = self.transform(img)
>   File "/home/toshi/base/lib/python3.9/site-packages/torchvision/transforms/transforms.py", line 67, in __call__
>     img = t(img)
>   File "/home/toshi/base/lib/python3.9/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/toshi/base/lib/python3.9/site-packages/torchvision/transforms/transforms.py", line 823, in forward
>     i, j, h, w = self.get_params(img, self.scale, self.ratio)
>   File "/home/toshi/base/lib/python3.9/site-packages/torchvision/transforms/transforms.py", line 786, in get_params
>     target_area = area * torch.empty(1).uniform_(scale[0], scale[1]).item()
>   File "/home/toshi/base/lib/python3.9/site-packages/torch/cuda/__init__.py", line 163, in _lazy_init
>     raise RuntimeError(
> RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
> ```

**Comment by hongjoon0805** [comment]
The reason for the above error is in line 59 in main.py file. The pytorch version in our experiment setting was 1.0.0, and this version does not make any errors. If you use latest version, please erase the line 59 in main.py

Thanks
